language: cpp

install:
  # Download and build premake5 from source; the Travis environment doesn't have the right version of glibc6 for the prebuilt binaries to work.
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha6/premake-5.0.0-alpha6-src.zip -O premake.zip
  - unzip premake.zip
  - cd premake-5.0.0-alpha6/build/gmake.unix
  - make config=release
  - cd ../../..
  - mv premake-5.0.0-alpha6/bin/release/premake5 premake5
  
# Run premake to generate makefiles.
# Have to cd into directory and back out since premake5 doesn't appear to accept a directory argument.
before_script:
  - cd Compile/premake/Projects && ../../../premake5 gmake && cd ../../../
  
script: 
  - cd Compile/gnu.linux && make CONFIG=Release
